import Topo from "@/componentes/Topo/Topo";
import Rodape from"@/componentes/Rodape/rodape"


import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      
      <body>
      <Topo/>

        {children}
      <Rodape/>
      </body>
    </html>
  );
}
