'use client';
import Head from "next/head";
import { useState } from "react";
import Image from "next/image";
import estilos from "./page.module.css";
import Topo from"@/app/componentes/Topo"
import Footer from"@/app/componentes/footer"
import Banner from "@/app/componentes/secaobanner"
import Experiencia from "./componentes/SecaoExperienciaTrabalho";
import Card from"@/app/componentes/Card"

export default function Home() {
  const [alterarTema, setAlterarTema] = useState(false)

  function trocarTemaPagina(){
    setAlterarTema(!alterarTema)
  };

  return (
    <>
    <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin></link>
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700;800;900&display=swap" rel="stylesheet"></link>
    </Head>
    <main>
     <Topo clickAlterarCor={trocarTemaPagina} alterarCor={alterarTema} />
     <Banner alterarCor={alterarTema}/>
     <Experiencia alterarCor={alterarTema}/>
     <Footer alterarCor={alterarTema}/>
    </main>
    </>
  );
}
