'use client';
import { useState } from "react";
import { produtos } from "./produtos";
import estilos from "./page.module.css";
import Head from "next/head";
import Topo from "./componentes/Topo/topo";
import Categorias from "./componentes/categorias/categorias";
import Campodebusca from "./componentes/campodebusca/Campodebusca";
import Cards from "./componentes/cards/Cards"
import {produtosEntradas,buscarpratos,filtrarpratos,retornarpratos} from "./servicos/index"

export default function Home() {

  const [dadosFiltrados, setDadosFiltrados] = useState(produtosEntradas);
  const [textoBusca, setTextoBusca] = useState("");

  const [botaoClicado, setBotaoClicado] = useState("Entradas");

  const handleFiltrarpratos = (categoria) => {
    setDadosFiltrados(filtrarpratos(categoria));
    setTextoBusca("")
    setBotaoClicado(categoria);
  };

  const handleBuscarPratos = (textoDigitado) => {
    setTextoBusca(textoDigitado);
    textoDigitado.length >= 3 && setDadosFiltrados(buscarpratos(textoDigitado));
    setDadosFiltrados(buscarpratos(textoDigitado));
  };

  const handleLimparFiltro = () => {
    setListapratos(retornarpratos());
    setTextoBusca("");
  };

  return (
    <>
    <Head>
    <title>RESTAURANT</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
        <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet"/>

    </Head>
    <header className={estilos.container_topo}>
      <Topo/>
    </header>
    <main className={estilos.container_principal}>
      <Categorias
       botaoClicado={botaoClicado}
       handleFiltrarpratos={handleFiltrarpratos}/>
      <Campodebusca
       handleBuscarPratos={handleBuscarPratos}
       textoBusca={textoBusca}/>
        <h1 className={estilos.titulo_cardapio}>Cardapio</h1>
      <div className={estilos.card_container}>
        {dadosFiltrados.map((produto) => (
        <Cards key={produto.id} produto={produto}/>
        ))}
      </div>
    </main>
    </>
  );
}
