import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Topo from "@/componentes/Topo";
import Capa from "@/componentes/secaocapa"
import Produtos from "@/componentes/SeçãoProdutos";
import Sobre from "@/componentes/SeçãoSobre";
import Contato from "@/componentes/SeçãoContato";
import Rodape from "@/componentes/Rodape"
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
          <Topo/>
          <Capa/>
          <Produtos/>
          <Sobre/>
          <Contato/>
          <Rodape/>
      </main>
    </>
  );
}
