import estilos from "./categorias.module.css"
import Head from "next/head"
import Entradas from "../../../../public/Assets/entrada.png"
import Massas from "../../../../public/Assets/massa.png"
import Carnes from "../../../../public/Assets/carne.png"
import Bebidas from "../../../../public/Assets/bebidas.png"
import Saladas from "../../../../public/Assets/salada.png"
import Sobremesas from "../../../../public/Assets/sobremesa.png"
import Image from "next/image"

const Categorias = ({handleFiltrarpratos,botaoClicado}) => {

    return(
        <>
        <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin></link>
        <link href="https://fonts.googleapis.com/css2?family=Dancing+Script&family=Poppins&display=swap" rel="stylesheet"></link>
        </Head>
        <section className={estilos.container_principal}>
           <button className={botaoClicado === "Entradas" ? estilos.botaoAmarelo : estilos.botaoverde} onClick={() => handleFiltrarpratos("Entradas")}><Image src={Entradas} className={estilos.img}/>Entradas</button>
           <button className={botaoClicado === "Massas" ? estilos.botaoAmarelo : estilos.botaoverde} onClick={() => handleFiltrarpratos("Massas")}><Image src={Massas} className={estilos.img}/>Massas</button>
           <button className={botaoClicado === "Carnes" ? estilos.botaoAmarelo : estilos.botaoverde} onClick={() => handleFiltrarpratos("Carnes")}><Image src={Carnes} className={estilos.img}/> Carnes</button>
           <button className={botaoClicado === "Bebidas" ? estilos.botaoAmarelo : estilos.botaoverde} onClick={() => handleFiltrarpratos("Bebidas")}><Image src={Bebidas} className={estilos.img}/> Bebidas</button>
           <button className={botaoClicado === "Saladas" ? estilos.botaoAmarelo : estilos.botaoverde} onClick={() => handleFiltrarpratos("Saladas")}><Image src={Saladas} className={estilos.img}/> Saladas</button>
           <button className={botaoClicado === "Sobremesas" ? estilos.botaoAmarelo : estilos.botaoverde} onClick={() => handleFiltrarpratos("Sobremesas")}><Image src={Sobremesas} className={estilos.img}/> Sobremesas</button>
        </section>
        </>
    )
}
export default Categorias;